asyncapi: 3.0.0
info:
  title: Product Inventory Distribution
  version: 12.0.3
  description: >-
    BIAN Service Domain (expanded with the BIAN BOM) | Administer the
    provisioning and distribution of product inventory across the branch network
    and/or distribute direct to customers (e.g. mail) where appropriate
channels:
  ProductInventoryDistributionAdministrativePlan/Created:
    address: ProductInventoryDistributionAdministrativePlan/Created
    messages:
      ProductInventoryDistributionAdministrativePlan-created.message:
        $ref: '#/components/messages/ProductInventoryDistributionAdministrativePlan'
    description: ''
  ProductInventoryDistributionAdministrativePlan/Updated:
    address: ProductInventoryDistributionAdministrativePlan/Updated
    messages:
      ProductInventoryDistributionAdministrativePlan-updated.message:
        $ref: '#/components/messages/ProductInventoryDistributionAdministrativePlan'
    description: ''
  Oversight/Created:
    address: Oversight/Created
    messages:
      publish.message:
        $ref: '#/components/messages/Oversight'
    description: ''
  Oversight/Updated:
    address: Oversight/Updated
    messages:
      publish.message:
        $ref: '#/components/messages/Oversight'
    description: ''
  Provisioning/Created:
    address: Provisioning/Created
    messages:
      publish.message:
        $ref: '#/components/messages/Provisioning'
    description: ''
  Provisioning/Updated:
    address: Provisioning/Updated
    messages:
      publish.message:
        $ref: '#/components/messages/Provisioning'
    description: ''
  Distribution/Created:
    address: Distribution/Created
    messages:
      publish.message:
        $ref: '#/components/messages/Distribution'
    description: ''
  Distribution/Updated:
    address: Distribution/Updated
    messages:
      publish.message:
        $ref: '#/components/messages/Distribution'
    description: ''
  ProductInventoryDistributionOutcome/Created:
    address: ProductInventoryDistributionOutcome/Created
    messages:
      publish.message:
        $ref: '#/components/messages/ProductInventoryDistributionOutcome'
    description: ''
  ProductInventoryDistributionOutcome/Updated:
    address: ProductInventoryDistributionOutcome/Updated
    messages:
      publish.message:
        $ref: '#/components/messages/ProductInventoryDistributionOutcome'
    description: ''
  Mailing/Created:
    address: Mailing/Created
    messages:
      publish.message:
        $ref: '#/components/messages/Mailing'
    description: ''
  Mailing/Updated:
    address: Mailing/Updated
    messages:
      publish.message:
        $ref: '#/components/messages/Mailing'
    description: ''
operations:
  ProductInventoryDistributionAdministrativePlan-created:
    action: receive
    channel:
      $ref: '#/channels/ProductInventoryDistributionAdministrativePlan~1Created'
    summary: ProductInventoryDistributionAdministrativePlan
    messages:
      - $ref: >-
          #/channels/ProductInventoryDistributionAdministrativePlan~1Created/messages/ProductInventoryDistributionAdministrativePlan-created.message
  ProductInventoryDistributionAdministrativePlan-updated:
    action: receive
    channel:
      $ref: '#/channels/ProductInventoryDistributionAdministrativePlan~1Updated'
    summary: ProductInventoryDistributionAdministrativePlan
    messages:
      - $ref: >-
          #/channels/ProductInventoryDistributionAdministrativePlan~1Updated/messages/ProductInventoryDistributionAdministrativePlan-updated.message
  Oversight/Created.publish:
    action: receive
    channel:
      $ref: '#/channels/Oversight~1Created'
    summary: Oversight
    messages:
      - $ref: '#/channels/Oversight~1Created/messages/publish.message'
  Oversight/Updated.publish:
    action: receive
    channel:
      $ref: '#/channels/Oversight~1Updated'
    summary: Oversight
    messages:
      - $ref: '#/channels/Oversight~1Updated/messages/publish.message'
  Provisioning/Created.publish:
    action: receive
    channel:
      $ref: '#/channels/Provisioning~1Created'
    summary: Provisioning
    messages:
      - $ref: '#/channels/Provisioning~1Created/messages/publish.message'
  Provisioning/Updated.publish:
    action: receive
    channel:
      $ref: '#/channels/Provisioning~1Updated'
    summary: Provisioning
    messages:
      - $ref: '#/channels/Provisioning~1Updated/messages/publish.message'
  Distribution/Created.publish:
    action: receive
    channel:
      $ref: '#/channels/Distribution~1Created'
    summary: Distribution
    messages:
      - $ref: '#/channels/Distribution~1Created/messages/publish.message'
  Distribution/Updated.publish:
    action: receive
    channel:
      $ref: '#/channels/Distribution~1Updated'
    summary: Distribution
    messages:
      - $ref: '#/channels/Distribution~1Updated/messages/publish.message'
  ProductInventoryDistributionOutcome/Created.publish:
    action: receive
    channel:
      $ref: '#/channels/ProductInventoryDistributionOutcome~1Created'
    summary: ProductInventoryDistributionOutcome
    messages:
      - $ref: >-
          #/channels/ProductInventoryDistributionOutcome~1Created/messages/publish.message
  ProductInventoryDistributionOutcome/Updated.publish:
    action: receive
    channel:
      $ref: '#/channels/ProductInventoryDistributionOutcome~1Updated'
    summary: ProductInventoryDistributionOutcome
    messages:
      - $ref: >-
          #/channels/ProductInventoryDistributionOutcome~1Updated/messages/publish.message
  Mailing/Created.publish:
    action: receive
    channel:
      $ref: '#/channels/Mailing~1Created'
    summary: Mailing
    messages:
      - $ref: '#/channels/Mailing~1Created/messages/publish.message'
  Mailing/Updated.publish:
    action: receive
    channel:
      $ref: '#/channels/Mailing~1Updated'
    summary: Mailing
    messages:
      - $ref: '#/channels/Mailing~1Updated/messages/publish.message'
components:
  messages:
    ProductInventoryDistributionAdministrativePlan:
      name: ProductInventoryDistributionAdministrativePlan
      description: >-
        Handle and assign the day to day activities, capture time, costs and
        income for an operational unit  within Product Inventory Distribution. 

        Example: Administer the time reporting and billing for the specialist
        sales support team.
      payload:
        $ref: '#/components/schemas/ProductInventoryDistributionAdministrativePlan'
    Oversight:
      name: Oversight
      description: >-
        Handle and assign the day to day activities, capture time, costs and
        income for an operational unit  within Product Inventory Distribution. 

        Example: Administer the time reporting and billing for the specialist
        sales support team.
      payload:
        $ref: '#/components/schemas/Oversight'
    Provisioning:
      name: Provisioning
      description: >-
        Handle and assign the day to day activities, capture time, costs and
        income for an operational unit  within Product Inventory Distribution. 

        Example: Administer the time reporting and billing for the specialist
        sales support team.
      payload:
        $ref: '#/components/schemas/Provisioning'
    Distribution:
      name: Distribution
      description: >-
        Handle and assign the day to day activities, capture time, costs and
        income for an operational unit  within Product Inventory Distribution. 

        Example: Administer the time reporting and billing for the specialist
        sales support team.
      payload:
        $ref: '#/components/schemas/Distribution'
    ProductInventoryDistributionOutcome:
      name: ProductInventoryDistributionOutcome
      description: >-
        Handle and assign the day to day activities, capture time, costs and
        income for an operational unit  within Product Inventory Distribution. 

        Example: Administer the time reporting and billing for the specialist
        sales support team.
      payload:
        $ref: '#/components/schemas/ProductInventoryDistributionOutcome'
    Mailing:
      name: Mailing
      description: >-
        Handle and assign the day to day activities, capture time, costs and
        income for an operational unit  within Product Inventory Distribution. 

        Example: Administer the time reporting and billing for the specialist
        sales support team.
      payload:
        $ref: '#/components/schemas/Mailing'
  schemas:
    Oversight:
      type: object
      description: >-
        Handle and assign the day to day activities, capture time, costs and
        income for an operational unit  within Product Inventory Distribution. 

        Example: Administer the time reporting and billing for the specialist
        sales support team.
      properties:
        OversightPreconditions:
          type: string
          format: String
          description: "The required status/situation before the routine can be undertaken \r\n"
        OversightBusinessUnitEmployeeReference:
          type: string
          format: Object
          description: "The operating unit/employee responsible for performing the routine \r\n"
        OversightWorkSchedule:
          type: string
          format: String
          description: "The timing and key actions/milestones involved in completing the routine \r\n"
        AdministrativeOversight:
          $ref: '#/components/schemas/BusinessService'
        OversightPostconditions:
          type: string
          format: String
          description: "The completion status once the routine has been completed (note the need to fulfill a routine may recur frequently) \r\n"
        OversightAdministrativeOversightServiceType:
          type: string
          format: String
          description: "Reference to the specific business service type \r\n"
        OversightAdministrativeOversightServiceDescription:
          type: string
          format: String
          description: "Description of the performed business service \r\n"
        OversightAdministrativeOversightServiceInputsandOuputs:
          type: string
          format: String
          description: "Mandatory and optional inputs and output information for the business service \r\n"
        OversightAdministrativeOversightServiceWorkProduct:
          type: string
          format: String
          description: "Documentation, meeting schedules, notes, reasearch. calculations and any other work products produced by the business service \r\n"
        OversightAdministrativeOversightServiceName:
          type: string
          format: String
          description: ''
    BusinessService:
      type: object
      format: BusinessService
      description: "The Product Inventory Distribution AdministrativePlan specific Business Service \r\n"
      properties:
        Businessservicetypevalues:
          enum:
            - Businessservicetypevalues
          format: BusinessService
    Provisioning:
      type: object
      description: >-
        Handle and assign the day to day activities, capture time, costs and
        income for an operational unit  within Product Inventory Distribution. 

        Example: Administer the time reporting and billing for the specialist
        sales support team.
      properties:
        ProvisioningPreconditions:
          type: string
          format: String
          description: "The required status/situation before the routine can be undertaken \r\n"
        ProvisioningBusinessUnitEmployeeReference:
          type: string
          format: Object
          description: "The operating unit/employee responsible for performing the routine \r\n"
        ProvisioningWorkSchedule:
          type: string
          format: String
          description: "The timing and key actions/milestones involved in completing the routine \r\n"
        BusinessService:
          $ref: '#/components/schemas/BusinessService'
        ProvisioningPostconditions:
          type: string
          format: String
          description: "The completion status once the routine has been completed (note the need to fulfill a routine may recur frequently) \r\n"
        ProvisioningServiceType:
          type: string
          format: String
          description: "Reference to the specific business service type \r\n"
        ProvisioningServiceDescription:
          type: string
          format: String
          description: "Description of the performed business service \r\n"
        ProvisioningServiceInputsandOuputs:
          type: string
          format: String
          description: "Mandatory and optional inputs and output information for the business service \r\n"
        ProvisioningServiceWorkProduct:
          type: string
          format: String
          description: "Documentation, meeting schedules, notes, reasearch. calculations and any other work products produced by the business service \r\n"
        ProvisioningServiceName:
          type: string
          format: String
          description: ''
    Distribution:
      type: object
      description: >-
        Handle and assign the day to day activities, capture time, costs and
        income for an operational unit  within Product Inventory Distribution. 

        Example: Administer the time reporting and billing for the specialist
        sales support team.
      properties:
        DistributionPreconditions:
          type: string
          format: String
          description: "The required status/situation before the routine can be undertaken \r\n"
        DistributionBusinessUnitEmployeeReference:
          type: string
          format: Object
          description: "The operating unit/employee responsible for performing the routine \r\n"
        DistributionWorkSchedule:
          type: string
          format: String
          description: "The timing and key actions/milestones involved in completing the routine \r\n"
        BusinessService:
          $ref: '#/components/schemas/BusinessService'
        DistributionPostconditions:
          type: string
          format: String
          description: "The completion status once the routine has been completed (note the need to fulfill a routine may recur frequently) \r\n"
        DistributionServiceType:
          type: string
          format: String
          description: "Reference to the specific business service type \r\n"
        DistributionServiceDescription:
          type: string
          format: String
          description: "Description of the performed business service \r\n"
        DistributionServiceInputsandOuputs:
          type: string
          format: String
          description: "Mandatory and optional inputs and output information for the business service \r\n"
        DistributionServiceWorkProduct:
          type: string
          format: String
          description: "Documentation, meeting schedules, notes, reasearch. calculations and any other work products produced by the business service \r\n"
        DistributionServiceName:
          type: string
          format: String
          description: ''
    ProductInventoryDistributionOutcome:
      type: object
      description: >-
        Handle and assign the day to day activities, capture time, costs and
        income for an operational unit  within Product Inventory Distribution. 

        Example: Administer the time reporting and billing for the specialist
        sales support team.
      properties:
        ProductInventoryDistributionPerformanceAnalysis:
          type: string
          format: String
          description: ''
        ProductInventoryDistributionActivityAnalysis:
          type: string
          format: String
          description: ''
        ProductInventoryDistributionAdministrativePlan:
          type: string
          format: String
          description: ''
        ProductInventoryDistributionAdministrationTask:
          type: string
          format: String
          description: ''
    Mailing:
      type: object
      description: >-
        Handle and assign the day to day activities, capture time, costs and
        income for an operational unit  within Product Inventory Distribution. 

        Example: Administer the time reporting and billing for the specialist
        sales support team.
      properties:
        MailingPreconditions:
          type: string
          format: String
          description: "The required status/situation before the routine can be undertaken \r\n"
        MailingBusinessUnitEmployeeReference:
          type: string
          format: Object
          description: "The operating unit/employee responsible for performing the routine \r\n"
        MailingWorkSchedule:
          type: string
          format: String
          description: "The timing and key actions/milestones involved in completing the routine \r\n"
        Mailing:
          $ref: '#/components/schemas/BusinessService'
        MailingPostconditions:
          type: string
          format: String
          description: "The completion status once the routine has been completed (note the need to fulfill a routine may recur frequently) \r\n"
        MailingMailingServiceType:
          type: string
          format: String
          description: "Reference to the specific business service type \r\n"
        MailingMailingServiceDescription:
          type: string
          format: String
          description: "Description of the performed business service \r\n"
        MailingMailingServiceInputsandOuputs:
          type: string
          format: String
          description: "Mandatory and optional inputs and output information for the business service \r\n"
        MailingMailingServiceWorkProduct:
          type: string
          format: String
          description: "Documentation, meeting schedules, notes, reasearch. calculations and any other work products produced by the business service \r\n"
        MailingMailingServiceName:
          type: string
          format: String
          description: ''
    ProductInventoryDistributionAdministrativePlan:
      type: object
      description: >-
        Handle and assign the day to day activities, capture time, costs and
        income for an operational unit  within Product Inventory Distribution. 

        Example: Administer the time reporting and billing for the specialist
        sales support team.
      properties:
        ProductInventoryDistributionAdministrativePlanBudgetType:
          type: string
          format: String
          description: "A Classification value that distinguishes between Budgets within Product Inventory Distribution AdministrativePlan according to the type of resource and/or activity that is budgetted \r\n"
        ProductInventoryDistributionAdministrativePlanBudget:
          type: string
          format: String
          description: "An estimate of costs, revenues, and resources  over a specified period which is defined for Product Inventory Distribution AdministrativePlan \r\n"
        ProductInventoryDistributionAdministrativePlanAssignment:
          type: string
          format: String
          description: "The allocation of someone or something which is specified for Product Inventory Distribution AdministrativePlan \r\n"
        ProductInventoryDistributionAdministrativePlanPlan:
          type: string
          format: String
          description: "A plan that defines clerical support for ProductInventoryDistribution \r\n"
        ProductInventoryDistributionAdministrativePlanReference:
          type: string
          format: Object
          description: "Party who is involved in  Product Inventory Distribution AdministrativePlan \r\n"
