asyncapi: 3.0.0
info:
  title: Product Design
  version: 12.0.3
  description: >-
    BIAN Service Domain (expanded with the BIAN BOM) | Develop/refine product
    designs and supporting specification details
channels:
  ProductorServiceSpecification/Created:
    address: ProductorServiceSpecification/Created
    messages:
      ProductorServiceSpecification-created.message:
        $ref: '#/components/messages/ProductorServiceSpecification'
    description: ''
  ProductorServiceSpecification/Updated:
    address: ProductorServiceSpecification/Updated
    messages:
      ProductorServiceSpecification-updated.message:
        $ref: '#/components/messages/ProductorServiceSpecification'
    description: ''
  Testing/Created:
    address: Testing/Created
    messages:
      publish.message:
        $ref: '#/components/messages/Testing'
    description: ''
  Testing/Updated:
    address: Testing/Updated
    messages:
      publish.message:
        $ref: '#/components/messages/Testing'
    description: ''
  Production/Created:
    address: Production/Created
    messages:
      publish.message:
        $ref: '#/components/messages/Production'
    description: ''
  Production/Updated:
    address: Production/Updated
    messages:
      publish.message:
        $ref: '#/components/messages/Production'
    description: ''
  FunctionalRequirements/Created:
    address: FunctionalRequirements/Created
    messages:
      publish.message:
        $ref: '#/components/messages/FunctionalRequirements'
    description: ''
  FunctionalRequirements/Updated:
    address: FunctionalRequirements/Updated
    messages:
      publish.message:
        $ref: '#/components/messages/FunctionalRequirements'
    description: ''
operations:
  ProductorServiceSpecification-created:
    action: receive
    channel:
      $ref: '#/channels/ProductorServiceSpecification~1Created'
    summary: ProductorServiceSpecification
    messages:
      - $ref: >-
          #/channels/ProductorServiceSpecification~1Created/messages/ProductorServiceSpecification-created.message
  ProductorServiceSpecification-updated:
    action: receive
    channel:
      $ref: '#/channels/ProductorServiceSpecification~1Updated'
    summary: ProductorServiceSpecification
    messages:
      - $ref: >-
          #/channels/ProductorServiceSpecification~1Updated/messages/ProductorServiceSpecification-updated.message
  Testing/Created.publish:
    action: receive
    channel:
      $ref: '#/channels/Testing~1Created'
    summary: Testing
    messages:
      - $ref: '#/channels/Testing~1Created/messages/publish.message'
  Testing/Updated.publish:
    action: receive
    channel:
      $ref: '#/channels/Testing~1Updated'
    summary: Testing
    messages:
      - $ref: '#/channels/Testing~1Updated/messages/publish.message'
  Production/Created.publish:
    action: receive
    channel:
      $ref: '#/channels/Production~1Created'
    summary: Production
    messages:
      - $ref: '#/channels/Production~1Created/messages/publish.message'
  Production/Updated.publish:
    action: receive
    channel:
      $ref: '#/channels/Production~1Updated'
    summary: Production
    messages:
      - $ref: '#/channels/Production~1Updated/messages/publish.message'
  FunctionalRequirements/Created.publish:
    action: receive
    channel:
      $ref: '#/channels/FunctionalRequirements~1Created'
    summary: FunctionalRequirements
    messages:
      - $ref: '#/channels/FunctionalRequirements~1Created/messages/publish.message'
  FunctionalRequirements/Updated.publish:
    action: receive
    channel:
      $ref: '#/channels/FunctionalRequirements~1Updated'
    summary: FunctionalRequirements
    messages:
      - $ref: '#/channels/FunctionalRequirements~1Updated/messages/publish.message'
components:
  messages:
    ProductorServiceSpecification:
      name: ProductorServiceSpecification
      description: >-
        Create and maintain a design for a procedure, product/service model or
        other such entity  within Product Design. 

        Example: Create and maintain product designs and analytical models.
      payload:
        $ref: '#/components/schemas/ProductorServiceSpecification'
    Testing:
      name: Testing
      description: |-
        The main design elements/views making up the overall specification
        Examples:- Business Requirements
      payload:
        $ref: '#/components/schemas/Testing'
    Production:
      name: Production
      description: |-
        The main design elements/views making up the overall specification
        Examples:- Business Requirements
      payload:
        $ref: '#/components/schemas/Production'
    FunctionalRequirements:
      name: FunctionalRequirements
      description: |-
        The main design elements/views making up the overall specification
        Examples:- Business Requirements
      payload:
        $ref: '#/components/schemas/FunctionalRequirements'
  schemas:
    Testing:
      type: object
      description: |-
        The main design elements/views making up the overall specification
        Examples:- Business Requirements
      properties:
        ProductandServiceSpecificationTestReference:
          type: string
          format: Object
          description: "Reference to a type of product or service specification test \r\n"
        ProductandServiceSpecificationTestType:
          type: string
          format: String
          description: "Defines the type of test (e.g. user/consumer checks, profitability simulations, business acceptance etc.) \r\n"
        ProductandServiceSpecificationTestHarnessReference:
          type: string
          format: Object
          description: "Reference to the testing environment used to apply the test (can include production events and transactions to simulate performance) \r\n"
        ProductandServiceSpecificationTestResult:
          type: string
          format: String
          description: "Record of testing applied to the product or service specification \r\n"
        ProductandServiceSpecificationTestingTaskReference:
          type: string
          format: Object
          description: "Reference to a type of testing activity \r\n"
        ProductandServiceSpecificationTestingTaskRecord:
          type: string
          format: String
          description: "The record of work products used for this testing activity \r\n"
        ProductandServiceSpecificationComplianceTaskReference:
          type: string
          format: Object
          description: "Reference to compliance conformance check for the specification \r\n"
        ProductandServiceSpecificationComplianceTaskRecord:
          type: string
          format: String
          description: "Record of the compliance conformance check for the specification \r\n"
        ProductandServiceSpecificationComplianceTestReference:
          type: string
          format: Object
          description: "Reference to a compliance task performed against the specification \r\n"
        ProductandServiceSpecificationComplianceTestType:
          type: string
          format: String
          description: "Record of the compliance test applied to the specification \r\n"
    Production:
      type: object
      description: |-
        The main design elements/views making up the overall specification
        Examples:- Business Requirements
      properties:
        ProductandServiceSpecificationOperationalRequirements:
          type: string
          format: String
          description: "Specification of the operational and technical requirements \r\n"
        ProductandServiceSpecificationAllowedUsage:
          type: string
          format: String
          description: "Defines rules and suitability for the product or service usage \r\n"
        ProductandServiceSpecificationUsageGuidelines:
          type: string
          format: String
          description: "Provides guidance on the use of the product or service \r\n"
    FunctionalRequirements:
      type: object
      description: |-
        The main design elements/views making up the overall specification
        Examples:- Business Requirements
      properties:
        ProductandServiceSpecificationDesignTaskReference:
          type: string
          format: Object
          description: "Reference to a type of functional requirements specification activity \r\n"
        ProductandServiceSpecificationDesignTaskRecord:
          type: string
          format: String
          description: "The record of work products used for the design task \r\n"
        MarketResearchDataServiceReference:
          type: string
          format: Object
          description: "Reference to external service information provider used to obtain product or service related market research as input to the design \r\n"
        MarketResearchDataRecord:
          type: string
          format: String
          description: "Record of the product or service related market research \r\n"
        ProductandServiceFeedbackRecord:
          type: string
          format: String
          description: "User provided and solicited feedback, suggestions for product or service refinement \r\n"
        ProductandServiceRequirementsSpecification:
          type: string
          format: String
          description: "The product or service detailed functional requirements specification (with versioning as appropriate) \r\n"
    ProductorServiceSpecification:
      type: object
      description: >-
        Create and maintain a design for a procedure, product/service model or
        other such entity  within Product Design. 

        Example: Create and maintain product designs and analytical models.
      properties:
        ProductandServiceType:
          type: string
          format: String
          description: "The type or category of product or service (e.g. specialized consumer loan, relocation services) \r\n"
        ProductandServiceDescription:
          type: string
          format: String
          description: "A description of the product or service including its main features and target customer \r\n"
        ProductandServiceSpecificationDeployment:
          type: string
          format: String
          description: "Maintains the current production deployment configuration of the product or service \r\n"
        EmployeeBusinessUnitReference:
          type: string
          format: Object
          description: "Reference to the business units where the product or service is in use or supported \r\n"
        ProductandServiceSpecificationDeploymentConfiguration:
          type: string
          format: String
          description: "Details of the product or service specification deployment for reference \r\n"
        ProductandServiceSpecificationDeploymentTaskReference:
          type: string
          format: Object
          description: "Reference to the specification deployment task \r\n"
        ProductandServiceSpecificationDeploymentTaskRecord:
          type: string
          format: String
          description: "Recorded details of a specification deployment task \r\n"
        ProductandServiceSpecificationStatus:
          type: string
          format: String
          description: "The operational and development status of the product or service specification (e.g. under development, available, in-use under review) \r\n"
        ProductandServiceSpecificationUsage:
          type: string
          format: String
          description: "Tracking deployment and product or service usage frequency \r\n"
        ProductandServiceSpecificationImpact:
          type: string
          format: String
          description: "Track reporting of the performance/profitability (of specific features ) of the product or service specification \r\n"
        ProductandServiceSpecificationVersion:
          type: string
          format: String
          description: "Release version of the available specification plus version history as appropriate \r\n"
        ProductandServiceSpecification:
          type: string
          format: String
          description: "The deployable product or service specification in any appropriate form (including historical versions as appropriate). Note supporting systems and production/operations facilities are handled in parallel as part of a broader deployment \r\n"
