asyncapi: 3.0.0
info:
  title: Product Quality Assurance
  version: 12.0.3
  description: >-
    BIAN Service Domain (expanded with the BIAN BOM) | Maintain and execute a
    portfolio of product quality assurance tests and certifications that can be
    applied to evaluate any aspect of production activity for quality assurance
channels:
  ProductandServiceAssessment/Created:
    address: ProductandServiceAssessment/Created
    messages:
      ProductandServiceAssessment-created.message:
        $ref: '#/components/messages/ProductandServiceAssessment'
    description: ''
  ProductandServiceAssessment/Updated:
    address: ProductandServiceAssessment/Updated
    messages:
      ProductandServiceAssessment-updated.message:
        $ref: '#/components/messages/ProductandServiceAssessment'
    description: ''
  ProductQualityAssuranceOutcome/Created:
    address: ProductQualityAssuranceOutcome/Created
    messages:
      publish.message:
        $ref: '#/components/messages/ProductQualityAssuranceOutcome'
    description: ''
  ProductQualityAssuranceOutcome/Updated:
    address: ProductQualityAssuranceOutcome/Updated
    messages:
      publish.message:
        $ref: '#/components/messages/ProductQualityAssuranceOutcome'
    description: ''
  UsabilityChecks/Created:
    address: UsabilityChecks/Created
    messages:
      publish.message:
        $ref: '#/components/messages/UsabilityChecks'
    description: ''
  UsabilityChecks/Updated:
    address: UsabilityChecks/Updated
    messages:
      publish.message:
        $ref: '#/components/messages/UsabilityChecks'
    description: ''
  ResiliencyandPerformanceChecks/Created:
    address: ResiliencyandPerformanceChecks/Created
    messages:
      publish.message:
        $ref: '#/components/messages/ResiliencyandPerformanceChecks'
    description: ''
  ResiliencyandPerformanceChecks/Updated:
    address: ResiliencyandPerformanceChecks/Updated
    messages:
      publish.message:
        $ref: '#/components/messages/ResiliencyandPerformanceChecks'
    description: ''
  ProcessingErrorandIntegrityChecks/Created:
    address: ProcessingErrorandIntegrityChecks/Created
    messages:
      publish.message:
        $ref: '#/components/messages/ProcessingErrorandIntegrityChecks'
    description: ''
  ProcessingErrorandIntegrityChecks/Updated:
    address: ProcessingErrorandIntegrityChecks/Updated
    messages:
      publish.message:
        $ref: '#/components/messages/ProcessingErrorandIntegrityChecks'
    description: ''
  FunctionalConsistencyChecks/Created:
    address: FunctionalConsistencyChecks/Created
    messages:
      publish.message:
        $ref: '#/components/messages/FunctionalConsistencyChecks'
    description: ''
  FunctionalConsistencyChecks/Updated:
    address: FunctionalConsistencyChecks/Updated
    messages:
      publish.message:
        $ref: '#/components/messages/FunctionalConsistencyChecks'
    description: ''
operations:
  ProductandServiceAssessment-created:
    action: receive
    channel:
      $ref: '#/channels/ProductandServiceAssessment~1Created'
    summary: ProductandServiceAssessment
    messages:
      - $ref: >-
          #/channels/ProductandServiceAssessment~1Created/messages/ProductandServiceAssessment-created.message
  ProductandServiceAssessment-updated:
    action: receive
    channel:
      $ref: '#/channels/ProductandServiceAssessment~1Updated'
    summary: ProductandServiceAssessment
    messages:
      - $ref: >-
          #/channels/ProductandServiceAssessment~1Updated/messages/ProductandServiceAssessment-updated.message
  ProductQualityAssuranceOutcome/Created.publish:
    action: receive
    channel:
      $ref: '#/channels/ProductQualityAssuranceOutcome~1Created'
    summary: ProductQualityAssuranceOutcome
    messages:
      - $ref: >-
          #/channels/ProductQualityAssuranceOutcome~1Created/messages/publish.message
  ProductQualityAssuranceOutcome/Updated.publish:
    action: receive
    channel:
      $ref: '#/channels/ProductQualityAssuranceOutcome~1Updated'
    summary: ProductQualityAssuranceOutcome
    messages:
      - $ref: >-
          #/channels/ProductQualityAssuranceOutcome~1Updated/messages/publish.message
  UsabilityChecks/Created.publish:
    action: receive
    channel:
      $ref: '#/channels/UsabilityChecks~1Created'
    summary: UsabilityChecks
    messages:
      - $ref: '#/channels/UsabilityChecks~1Created/messages/publish.message'
  UsabilityChecks/Updated.publish:
    action: receive
    channel:
      $ref: '#/channels/UsabilityChecks~1Updated'
    summary: UsabilityChecks
    messages:
      - $ref: '#/channels/UsabilityChecks~1Updated/messages/publish.message'
  ResiliencyandPerformanceChecks/Created.publish:
    action: receive
    channel:
      $ref: '#/channels/ResiliencyandPerformanceChecks~1Created'
    summary: ResiliencyandPerformanceChecks
    messages:
      - $ref: >-
          #/channels/ResiliencyandPerformanceChecks~1Created/messages/publish.message
  ResiliencyandPerformanceChecks/Updated.publish:
    action: receive
    channel:
      $ref: '#/channels/ResiliencyandPerformanceChecks~1Updated'
    summary: ResiliencyandPerformanceChecks
    messages:
      - $ref: >-
          #/channels/ResiliencyandPerformanceChecks~1Updated/messages/publish.message
  ProcessingErrorandIntegrityChecks/Created.publish:
    action: receive
    channel:
      $ref: '#/channels/ProcessingErrorandIntegrityChecks~1Created'
    summary: ProcessingErrorandIntegrityChecks
    messages:
      - $ref: >-
          #/channels/ProcessingErrorandIntegrityChecks~1Created/messages/publish.message
  ProcessingErrorandIntegrityChecks/Updated.publish:
    action: receive
    channel:
      $ref: '#/channels/ProcessingErrorandIntegrityChecks~1Updated'
    summary: ProcessingErrorandIntegrityChecks
    messages:
      - $ref: >-
          #/channels/ProcessingErrorandIntegrityChecks~1Updated/messages/publish.message
  FunctionalConsistencyChecks/Created.publish:
    action: receive
    channel:
      $ref: '#/channels/FunctionalConsistencyChecks~1Created'
    summary: FunctionalConsistencyChecks
    messages:
      - $ref: >-
          #/channels/FunctionalConsistencyChecks~1Created/messages/publish.message
  FunctionalConsistencyChecks/Updated.publish:
    action: receive
    channel:
      $ref: '#/channels/FunctionalConsistencyChecks~1Updated'
    summary: FunctionalConsistencyChecks
    messages:
      - $ref: >-
          #/channels/FunctionalConsistencyChecks~1Updated/messages/publish.message
components:
  messages:
    ProductandServiceAssessment:
      name: ProductandServiceAssessment
      description: >-
        To test or assess an entity, possibly against some formal qualification
        or certification requirement  within Product Quality Assurance. 


        Examples:- Perform regulatory tests on a proposed financial transaction
        and check a new offer conforms to an existing contractual agreement.
      payload:
        $ref: '#/components/schemas/ProductandServiceAssessment'
    ProductQualityAssuranceOutcome:
      name: ProductQualityAssuranceOutcome
      description: |-
        All kind of verifications
        Examples:- Password verification
      payload:
        $ref: '#/components/schemas/ProductQualityAssuranceOutcome'
    UsabilityChecks:
      name: UsabilityChecks
      description: |-
        All kind of verifications
        Examples:- Password verification
      payload:
        $ref: '#/components/schemas/UsabilityChecks'
    ResiliencyandPerformanceChecks:
      name: ResiliencyandPerformanceChecks
      description: |-
        All kind of verifications
        Examples:- Password verification
      payload:
        $ref: '#/components/schemas/ResiliencyandPerformanceChecks'
    ProcessingErrorandIntegrityChecks:
      name: ProcessingErrorandIntegrityChecks
      description: |-
        All kind of verifications
        Examples:- Password verification
      payload:
        $ref: '#/components/schemas/ProcessingErrorandIntegrityChecks'
    FunctionalConsistencyChecks:
      name: FunctionalConsistencyChecks
      description: |-
        All kind of verifications
        Examples:- Password verification
      payload:
        $ref: '#/components/schemas/FunctionalConsistencyChecks'
  schemas:
    ProductQualityAssuranceOutcome:
      type: object
      description: |-
        All kind of verifications
        Examples:- Password verification
      properties:
        ProductQualityAssuranceWorkProduct:
          type: string
          format: String
          description: ''
        ProductQualityAssuranceAssessmentType:
          type: string
          format: String
          description: ''
    UsabilityChecks:
      type: object
      description: |-
        All kind of verifications
        Examples:- Password verification
      properties:
        UsabilityChecksPreconditions:
          type: string
          format: String
          description: "The required status/situation before the test can be applied \r\n"
        UsabilityChecksAnalysisSchedule:
          type: string
          format: String
          description: "The schedule and timing of the testing performed \r\n"
        UsabilityChecksVersionNumber:
          type: string
          format: String
          description: "The test version employed \r\n"
        UsabilityChecks:
          $ref: '#/components/schemas/BusinessService'
        UsabilityChecksServiceType:
          type: string
          format: String
          description: "Reference to the specific business service type \r\n"
        UsabilityChecksServiceDescription:
          type: string
          format: String
          description: "Description of the performed business service \r\n"
        UsabilityChecksServiceInputsandOuputs:
          type: string
          format: String
          description: "Mandatory and optional inputs and output information for the business service \r\n"
        UsabilityChecksServiceWorkProduct:
          type: string
          format: String
          description: "Documentation, meeting schedules, notes, reasearch. calculations and any other work products produced by the business service \r\n"
        UsabilityChecksServiceName:
          type: string
          format: String
          description: ''
    BusinessService:
      type: object
      format: BusinessService
      description: "The Product and  Service Assessment specific  Business Service \r\n"
      properties:
        Businessservicetypevalues:
          enum:
            - Businessservicetypevalues
          format: BusinessService
    ResiliencyandPerformanceChecks:
      type: object
      description: |-
        All kind of verifications
        Examples:- Password verification
      properties:
        ResiliencyandPerformanceChecksPreconditions:
          type: string
          format: String
          description: "The required status/situation before the test can be applied \r\n"
        ResiliencyandPerformanceChecksAnalysisSchedule:
          type: string
          format: String
          description: "The schedule and timing of the testing performed \r\n"
        ResiliencyandPerformanceChecksVersionNumber:
          type: string
          format: String
          description: "The test version employed \r\n"
        ResiliencyandPerformanceChecks:
          $ref: '#/components/schemas/BusinessService'
        ResiliencyandPerformanceChecksServiceType:
          type: string
          format: String
          description: "Reference to the specific business service type \r\n"
        ResiliencyandPerformanceChecksServiceDescription:
          type: string
          format: String
          description: "Description of the performed business service \r\n"
        ResiliencyandPerformanceChecksServiceInputsandOuputs:
          type: string
          format: String
          description: "Mandatory and optional inputs and output information for the business service \r\n"
        ResiliencyandPerformanceChecksServiceWorkProduct:
          type: string
          format: String
          description: "Documentation, meeting schedules, notes, reasearch. calculations and any other work products produced by the business service \r\n"
        ResiliencyandPerformanceChecksServiceName:
          type: string
          format: String
          description: ''
    ProcessingErrorandIntegrityChecks:
      type: object
      description: |-
        All kind of verifications
        Examples:- Password verification
      properties:
        ProcessingErrorandIntegrityChecksPreconditions:
          type: string
          format: String
          description: "The required status/situation before the test can be applied \r\n"
        ProcessingErrorandIntegrityChecksAnalysisSchedule:
          type: string
          format: String
          description: "The schedule and timing of the testing performed \r\n"
        ProcessingErrorandIntegrityChecksVersionNumber:
          type: string
          format: String
          description: "The test version employed \r\n"
        ProcessingErrorandIntegrityChecks:
          $ref: '#/components/schemas/BusinessService'
        ProcessingErrorandIntegrityChecksServiceType:
          type: string
          format: String
          description: "Reference to the specific business service type \r\n"
        ProcessingErrorandIntegrityChecksServiceDescription:
          type: string
          format: String
          description: "Description of the performed business service \r\n"
        ProcessingErrorandIntegrityChecksServiceInputsandOuputs:
          type: string
          format: String
          description: "Mandatory and optional inputs and output information for the business service \r\n"
        ProcessingErrorandIntegrityChecksServiceWorkProduct:
          type: string
          format: String
          description: "Documentation, meeting schedules, notes, reasearch. calculations and any other work products produced by the business service \r\n"
        ProcessingErrorandIntegrityChecksServiceName:
          type: string
          format: String
          description: ''
    FunctionalConsistencyChecks:
      type: object
      description: |-
        All kind of verifications
        Examples:- Password verification
      properties:
        FunctionalConsistencyChecksPreconditions:
          type: string
          format: String
          description: "The required status/situation before the test can be applied \r\n"
        FunctionalConsistencyChecksAnalysisSchedule:
          type: string
          format: String
          description: "The schedule and timing of the testing performed \r\n"
        FunctionalConsistencyChecksVersionNumber:
          type: string
          format: String
          description: "The test version employed \r\n"
        FunctionalConsistencyChecks:
          $ref: '#/components/schemas/BusinessService'
        FunctionalConsistencyChecksServiceType:
          type: string
          format: String
          description: "Reference to the specific business service type \r\n"
        FunctionalConsistencyChecksServiceDescription:
          type: string
          format: String
          description: "Description of the performed business service \r\n"
        FunctionalConsistencyChecksServiceInputsandOuputs:
          type: string
          format: String
          description: "Mandatory and optional inputs and output information for the business service \r\n"
        FunctionalConsistencyChecksServiceWorkProduct:
          type: string
          format: String
          description: "Documentation, meeting schedules, notes, reasearch. calculations and any other work products produced by the business service \r\n"
        FunctionalConsistencyChecksServiceName:
          type: string
          format: String
          description: ''
    ProductandServiceAssessment:
      type: object
      description: >-
        To test or assess an entity, possibly against some formal qualification
        or certification requirement  within Product Quality Assurance. 


        Examples:- Perform regulatory tests on a proposed financial transaction
        and check a new offer conforms to an existing contractual agreement.
      properties:
        ProductandServiceAssessmentParameterType:
          type: string
          format: String
          description: "A Classification value that distinguishes between Assessments according to type of concern defined within Product and  Service Assessment . Eg Market Analysis, Risk Analysis, Perfomance Analysis, etc. \r\n"
        ProductandServiceAssessmentSelectedOption:
          type: string
          format: String
          description: "A selected optional business service as subject matter of assessment \r\n"
        ProductandServiceAssessmentType:
          type: string
          format: String
          description: "The type of Product and  Service Assessment \r\n"
        ProductandServiceAssessmentReference:
          type: string
          format: Object
          description: "Reference to Product and  Service Assessment \r\n"
        ProductandServiceAssessmentRequest:
          type: string
          format: String
          description: "Request to assess ProductandService \r\n"
        ProductandServiceAssessmentSchedule:
          type: string
          format: String
          description: "Timetable to assess ProductandService \r\n"
        ProductandServiceAssessmentStatus:
          type: string
          format: String
          description: "The status of Product and  Service Assessment \r\n"
        ProductandServiceAssessmentUsageLog:
          type: string
          format: String
          description: "Reference to the log of (usage) ativities/events of Product and  Service Assessment \r\n"
        ProductandServiceAssessmentAssociatedParty:
          type: string
          format: String
          description: "Party who is involved in Product and  Service Assessment \r\n"
        ProductandServiceAssessmentServiceProviderReference:
          type: string
          format: Object
          description: "Reference to the party who has provided Product and  Service Assessment \r\n"
        ProductandServiceAssessmentRequesterReference:
          type: string
          format: Object
          description: "Reference to the party who has requested Product and  Service Assessment \r\n"
