asyncapi: 3.0.0
info:
  title: Product Expert Sales Support
  version: 12.0.3
  description: >-
    BIAN Service Domain (expanded with the BIAN BOM) | Administer the
    availability and allocation of product specialists to support sales activity
channels:
  SalesSpecialistSupportAdministrativePlan/Created:
    address: SalesSpecialistSupportAdministrativePlan/Created
    messages:
      SalesSpecialistSupportAdministrativePlan-created.message:
        $ref: '#/components/messages/SalesSpecialistSupportAdministrativePlan'
    description: ''
  SalesSpecialistSupportAdministrativePlan/Updated:
    address: SalesSpecialistSupportAdministrativePlan/Updated
    messages:
      SalesSpecialistSupportAdministrativePlan-updated.message:
        $ref: '#/components/messages/SalesSpecialistSupportAdministrativePlan'
    description: ''
  Assignment/Created:
    address: Assignment/Created
    messages:
      publish.message:
        $ref: '#/components/messages/Assignment'
    description: ''
  Assignment/Updated:
    address: Assignment/Updated
    messages:
      publish.message:
        $ref: '#/components/messages/Assignment'
    description: ''
operations:
  SalesSpecialistSupportAdministrativePlan-created:
    action: receive
    channel:
      $ref: '#/channels/SalesSpecialistSupportAdministrativePlan~1Created'
    summary: SalesSpecialistSupportAdministrativePlan
    messages:
      - $ref: >-
          #/channels/SalesSpecialistSupportAdministrativePlan~1Created/messages/SalesSpecialistSupportAdministrativePlan-created.message
  SalesSpecialistSupportAdministrativePlan-updated:
    action: receive
    channel:
      $ref: '#/channels/SalesSpecialistSupportAdministrativePlan~1Updated'
    summary: SalesSpecialistSupportAdministrativePlan
    messages:
      - $ref: >-
          #/channels/SalesSpecialistSupportAdministrativePlan~1Updated/messages/SalesSpecialistSupportAdministrativePlan-updated.message
  Assignment/Created.publish:
    action: receive
    channel:
      $ref: '#/channels/Assignment~1Created'
    summary: Assignment
    messages:
      - $ref: '#/channels/Assignment~1Created/messages/publish.message'
  Assignment/Updated.publish:
    action: receive
    channel:
      $ref: '#/channels/Assignment~1Updated'
    summary: Assignment
    messages:
      - $ref: '#/channels/Assignment~1Updated/messages/publish.message'
components:
  messages:
    SalesSpecialistSupportAdministrativePlan:
      name: SalesSpecialistSupportAdministrativePlan
      description: >
        Handle and assign the day to day activities, capture time, costs and
        income for an operational unit within Product Expert Sales Support. 
      payload:
        $ref: '#/components/schemas/SalesSpecialistSupportAdministrativePlan'
    Assignment:
      name: Assignment
      description: >-
        A collection of one or more clerical routines that are to be followed to
        administer the operational unit/function


        Examples:- Time-sheet recording
      payload:
        $ref: '#/components/schemas/Assignment'
  schemas:
    Assignment:
      type: object
      format: Assignment
      description: >-
        A collection of one or more clerical routines that are to be followed to
        administer the operational unit/function


        Examples:- Time-sheet recording
      properties:
        SalesSpecialistSupportAssignmentRequestType:
          type: string
          format: String
          description: "Defines the type of assignment (e.g. in person, phone conference) \r\n"
        SalesSpecialistSupportAssignmentRequestRecord:
          type: string
          format: String
          description: "Contains details of the product specialist support request, in particular the product or service of interest and the specific topics to be covered \r\n"
        SalesSpecialistSupportAssignmentSessionWorkProducts:
          type: string
          format: String
          description: "File of any meeting notes, work products and administrative documentation generated during the assignment \r\n"
        SalesSpecialistSupportAssignmentLocation:
          type: string
          format: String
          description: "The location of the customer interaction (e.g. branch, phone, customer site) \r\n"
        SalesSpecialistSupportAssignmentFee:
          type: string
          format: String
          description: "Details of time and expenses booked and fees associated with the assignment and if appropriate reference to charges made to the customer \r\n"
        SalesSpecialistSupportAssignmentResult:
          type: string
          format: String
          description: "The result of the customer interaction, including any suggested follow-up tasks \r\n"
        DateType:
          type: string
          format: String
          description: "Key dates associated with the assignment (e.g. booking date, confirmation date, execution date, follow-up/evaluation date) \r\n"
        Date:
          type: string
          format: String
          description: "Value of the specific date type \r\n"
    SalesSpecialistSupportAdministrativePlan:
      type: object
      description: >
        Handle and assign the day to day activities, capture time, costs and
        income for an operational unit within Product Expert Sales Support. 
      properties:
        SalesSpecialistSupportResourceAllocationServiceSchedule:
          type: string
          format: String
          description: "Maintains the allocation records of available sales specialist service resources. This includes all past and future booking commitments \r\n"
        SalesSpecialistSupportResourceReference:
          type: string
          format: Object
          description: "Reference to a sales specialist support resource \r\n"
        SalesSpecialistSupportResourceRecord:
          type: string
          format: String
          description: "Details about a registered sales specialist support resource \r\n"
        SalesSpecialistSupportResourceQualificationProfile:
          type: string
          format: String
          description: "Details the qualification, expertise and level of experience of a servicing specialist \r\n"
        SalesSpecialistSupportLocationReference:
          type: string
          format: Object
          description: "Reference to the locations service by the resource where face to face meetings are required \r\n"
        SalesSpecialistSupportResourceAvailabilitySchedule:
          type: string
          format: String
          description: "Details the time the resource plans to be and is actually available for assignments \r\n"
        SalesSpecialistSupportResourceStatus:
          type: string
          format: String
          description: "Tracks the current status indicating availability for assignment \r\n"
        SalesSpecialistSupportResourceAssignmentRecord:
          type: string
          format: String
          description: "Reference to a consolidated record of assignment instances handled by the support resource. This is used to track utilization and performance \r\n"
